using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using TMPro;

public class ShopUIManager : MonoBehaviour
{
    [Header("Link to Existing Logic")]
    public ShopPanelController shopPanelController; // <--- Links to your original system

    [Header("Shop Title")]
    public TMP_Text shopTitleText;

    [Header("UI Panels")]
    public GameObject cardsGridPanel; 
    public GameObject detailedViewPanel; 
    
    [Header("Controller Support")]
    public GameObject firstSelectedInDetailedView; // Assign your Buy or Back button here
    
    [Header("Detailed View Elements")]
    public Image detailedCardBackgroundImage; // The large background frame
    public Image detailedIconImage; // The actual item icon inside the frame
    public TMP_Text detailedNameText;
    public TMP_Text detailedPriceText; 
    public TMP_Text detailedDescriptionText;
    
    private InteractiveShopCard currentlySelectedCard;

    void Start()
    {
        if (cardsGridPanel != null) cardsGridPanel.SetActive(true);
        if (detailedViewPanel != null) detailedViewPanel.SetActive(false);
    }

    public void OpenDetailedView(InteractiveShopCard clickedCard)
    {
        currentlySelectedCard = clickedCard;
        
        if (cardsGridPanel != null) cardsGridPanel.SetActive(false);
        if (detailedViewPanel != null) detailedViewPanel.SetActive(true);
        
        // Copy the visual data generated by ShopPanelController from the small card to the big card!
        if (detailedIconImage != null && clickedCard.iconImage != null) 
        {
            detailedIconImage.sprite = clickedCard.iconImage.sprite;
            detailedIconImage.enabled = clickedCard.iconImage.enabled;
        }
        
        if (detailedCardBackgroundImage != null && clickedCard.cardBackgroundImage != null)
        {
            detailedCardBackgroundImage.sprite = clickedCard.cardBackgroundImage.sprite;
            detailedCardBackgroundImage.color = clickedCard.cardBackgroundImage.color; // In case you use color tints!
        }
            
        if (detailedNameText != null && clickedCard.nameText != null) 
            detailedNameText.text = clickedCard.nameText.text;
            
        if (detailedPriceText != null && clickedCard.priceText != null) 
            detailedPriceText.text = clickedCard.priceText.text;
            
        if (detailedDescriptionText != null && clickedCard.modifiersText != null) 
            detailedDescriptionText.text = clickedCard.modifiersText.text;
            
        // Controller Support: Focus the Buy/Back button
        if (firstSelectedInDetailedView != null)
        {
            EventSystem.current.SetSelectedGameObject(firstSelectedInDetailedView);
        }
    }

    public void SetShopName(string townName)
    {
        if (shopTitleText != null)
        {
            shopTitleText.text = townName + "'s Shop";
        }
    }

    public void CloseDetailedView()
    {
        
        if (detailedViewPanel != null) detailedViewPanel.SetActive(false);
        if (cardsGridPanel != null) cardsGridPanel.SetActive(true);
        
        if (currentlySelectedCard != null)
        {
            // Controller Support: Refocus the card when going back to the grid
            EventSystem.current.SetSelectedGameObject(currentlySelectedCard.gameObject);
            
            currentlySelectedCard.ResetCard();
            currentlySelectedCard = null;
        }
    }
    
    public void BuyItem()
    {
        if (currentlySelectedCard != null && shopPanelController != null)
        {
            // Call the existing public Purchase method on ShopPanelController!
            shopPanelController.Purchase(currentlySelectedCard.slotIndex);
            
            // Close the detailed view after buying
            CloseDetailedView();
        }
    }
}


